### PR TITLE
borrow: suspensions

### PR DESCRIPTION
**Pull request by nimaai**
https://github.com/leihs/leihs/issues/1252

### CODE REVIEW

**Review by urs-van-binsbergen — COMMENTED** [review]
Tested, works fine! The date boundaries of the suspensions should be considered?

**Comment by nimaai** [comment]
> The date boundaries of the suspensions should be considered?

No: https://github.com/leihs/leihs/issues/1252#issuecomment-1034954291

**Comment by urs-van-binsbergen** [comment]
> A suspended user should not be able to send a reservation for AFTER the suspension
Ah I see, but this refers to something else: DURING the suspension period the user should not be able to order for the future (when the suspension period will be over). However when the period is OVER, he can order again.

**Comment by nimaai** [comment]
>However when the period is OVER, he can order again.

Correct! I will fix this.

**Review by urs-van-binsbergen — APPROVED** [review]

**Pull request merged**
