### PR TITLE
Release: 5.4.0

### PR DESCRIPTION
**Pull request by nimaai**
general release checks:
- [ ] has a milestone with a version number
- [ ] all issues in milestone are closed
- [ ] all issues in milestone have label "accepted"
- [ ] release notes are written
- [ ] optional: system test product owner
- [ ] optional: system test stakeholders

specific release checks:
- [ ]  SMTP settings work (also https://github.com/leihs/leihs/issues/995)
- [ ] refactored "view" tables (users/delegations): are all write operations disabled in legacy

### CODE REVIEW

**Comment by eins78** [comment]
@nimaai the release notes will have to mention the needed inventory changes:

> * copy the declaration of `leihs_external_hostname` from `settings/yourhost.yml` to `host_vars/yourhost.yml` file for this host. 
> * make sure the `leihs_external_hostname` `host_vars/yourhost.yml` defines the correct external hostname, with no scheme, e.g. `leihs_external_hostname: "leihs.example.org"`
> * make sure that all the other values in `config/settings.yml` are saved into the settings (see in DB or Admin UI). This will be the case if you have not changed the settings since the last deploy.
> * remove the folder `settings`

we can also link to a example commit where this is done in https://github.com/leihs/demo.leihs.zhdk.ch

**Comment by eins78** [comment]
@nimaai prepared demo inventory: https://github.com/leihs/demo.leihs.zhdk.ch/commit/383276c8796f8e455954a72b982d3c0356bb556c

**Comment by eins78** [comment]
more points for the release notes (from [slack](https://madek.slack.com/archives/C80TT63DM/p1612769679035200)):
* `users.login` is more strict about allowed characters
* "All Users" group replaces "make all users my customer" settings for pools
* breaking changes admin-API
* "New System-Admin Roles are introduced in additon to regular admins. After the automatic migration, please check the list of both kinds of Admins and ensure that all users have the minimal permissions needed)"

**Comment by nimaai** [comment]
Superseded by [Release: 6.0.0](https://github.com/leihs/leihs/pull/1044)

**Pull request closed without merging**
