### PR TITLE
borrow: refresh timeout logic change

### PR DESCRIPTION
**Pull request by nimaai**
https://github.com/leihs/leihs/issues/1215

### CODE REVIEW

**Comment by nimaai** [comment]
Criteria for making a reservation `draft`:
- invalid start date  (without considering `reservation_advance_days`)
- invalid start date (considering `reservation_advance_days`)
- max visits count reached on start or end date
- no access to inventory pool anymore
- new holiday on start or end date
- no workday on start or end date
- `settings.maximum_reservation_time` greater then `end_date - start_date`
- not timed out with invalid availability (e.g. due to retired item)
- timed out with invalid availability (quantity reserved by another user)

@eins78 anything I forgot?

**Comment by nimaai** [comment]
@eins78 the commented out lines in the test data of refresh timeout spec are things which are failing and have to be implemented.

**Comment by eins78** [comment]
> * not timed out with invalid availability (e.g. due to retired item)

There are many reasons for "item not available at all anymore", but they should all be included in this point (already handled by legacy)

**Comment by eins78** [comment]
todo spec:
* [ ] r2 and r3 should not have a start date of "today" because thats never valid (need to add `reservation_advance_days`)

LOG:

I looked at the test data in the UI:

* `r2_not_timed_out_with_invalid_avail_1`
  * edit panel has empty pools
  * must remove reservation to resolve
* `r3_timed_out_with_invalid_avail_1` and `_2`
  * must reduce quantity from 2 to 1 to resolve
* `r1_invalid_start_date`
  * must increase start date to resolve
* `r5_not_timed_out_ok`
* `r4_timed_out_ok`

Screen Shot 2021-11-09 at 15 58 55

**Pull request closed without merging**
