### PR TITLE
all users group instead of automatic access trigger

### PR DESCRIPTION
**Pull request by nimaai**
@DrTom https://github.com/leihs/leihs/issues/1016

To-Do:
- [x] **exclude delegations**

### CODE REVIEW

**Comment by nimaai** [comment]
https://github.com/leihs/zhdk-sync/issues/2#issuecomment-768973260 ?

**Comment by eins78** [comment]
@nimaai 🤔 Is there a reason why this is not using "generated UUIDs" like we do elsewhere (instead of referencing by name)?

**Comment by nimaai** [comment]
@eins78 Unique constraint on `groups.name`. Might be, that an "All users" group already exists and possibly have users in it (that's why `ON CONFLICT DO NOTHING`). I decided to assume that if such a group already exist, it is suppose to literally mean what the name suggests (even if for some reasons some users are not in it, yet).

Besides, I also assumed based on the description in the ticket (#1016) that we get rid of the trigger for good and that schools which are not using `automatic_access` for any pool decide, if they want such a group or not. Having just said that, I realized that this is not the case in the current migration. I will put it in the potential to-do if we decide continue going down this road...

**Comment by DrTom** [comment]
Ich sehe nicht den Trigger, der einen neue Benutzer zufügt wenn er erzeugt wird?  Was ich cool finde:
```INSERT INTO groups_users(group_id, user_id)
      SELECT '#{all_users_group.id}', id
      FROM users
      ON CONFLICT DO NOTHING```
vielleicht könnte man das aufrufen, immer wenn ein neuer user angelegt wird; dann sorgt das automatisch dafür, dass Benutzer die unabsichtlich entfernt wurden wieder rein kommen.

Im Kontext trigger vs sync. Das soll Unabhänging funktionieren. Also mit Trigger.

**Comment by DrTom** [comment]
Ich würde für die Gruppe eine Fixe v5 UUID verwenden; etwa https://uuidonline.com/?version=5&namespace=leihs_all_users so dass wir diese Gruppe  später mit der ID referenzieren können. Eventuell braucht es das auch wegen den seeds (bin mir nicht sicher). Wir könnten dann auch zulassen, dass jemand die Gruppe umbenennt (müssen wir nicht).

**Comment by DrTom** [comment]
Apropos, man sollte auch in der DB den einen oder anderen Constraint-Trigger machen, damit man diese Gruppe nicht löschen kann.

**Comment by nimaai** [comment]
@DrTom do we delete users in any way? If yes, then we need an additional trigger I guess, which removes the user from the group also.

**Comment by eins78** [comment]
> @DrTom do we delete user rows in any way? If yes, then we need an additional trigger I guess, which removes the user from the group before.

yes, there is "delete" and "merge and delete", see https://test.leihs.zhdk.ch/admin/users/e4da3cef-6a05-5b04-9ce6-2154286cfad9/delete

**Comment by nimaai** [comment]
I just checked, we have `ON DELETE CASCADE` on `groups_users` so it's handled already @DrTom.

**Pull request merged**
